from __future__ import annotations
from typing import Protocol, Any
from axiom_core.types import Observation, Action, EnvironmentStatus
class AxiomEnvironment(Protocol):
    def observe(self) -> Observation: ...
    def legal_actions(self) -> list[Action]: ...
    def execute(self, action: Action) -> Observation: ...
    def status(self) -> EnvironmentStatus: ...
    def snapshot(self) -> bytes | dict: ...
    def restore(self, snapshot: bytes | dict) -> None: ...
__all__=['AxiomEnvironment','Observation','Action','EnvironmentStatus']
